// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-IuGoRUIwa4yTluZVL6fTCDiE7VUJTqI',
    appId: '1:570384128780:web:7fd403787edf1bdcc40729',
    messagingSenderId: '570384128780',
    projectId: 'fixit-c7f0c',
    authDomain: 'fixit-c7f0c.firebaseapp.com',
    storageBucket: 'fixit-c7f0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj-zLCSyAbgq_f3DKcrscjFj6o_oO2sls',
    appId: '1:570384128780:android:8100990860155de1c40729',
    messagingSenderId: '570384128780',
    projectId: 'fixit-c7f0c',
    storageBucket: 'fixit-c7f0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTuNWxBhI0BY7a9VThwyBs0kQJ3TfmPs',
    appId: '1:570384128780:ios:94bcf62ca82c20efc40729',
    messagingSenderId: '570384128780',
    projectId: 'fixit-c7f0c',
    storageBucket: 'fixit-c7f0c.firebasestorage.app',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHTuNWxBhI0BY7a9VThwyBs0kQJ3TfmPs',
    appId: '1:570384128780:ios:94bcf62ca82c20efc40729',
    messagingSenderId: '570384128780',
    projectId: 'fixit-c7f0c',
    storageBucket: 'fixit-c7f0c.firebasestorage.app',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-IuGoRUIwa4yTluZVL6fTCDiE7VUJTqI',
    appId: '1:570384128780:web:d1bb2e80ec933bcdc40729',
    messagingSenderId: '570384128780',
    projectId: 'fixit-c7f0c',
    authDomain: 'fixit-c7f0c.firebaseapp.com',
    storageBucket: 'fixit-c7f0c.firebasestorage.app',
  );
}
